name: music_app1
description: App de música con playlists persistidas y reproducción en segundo plano.
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  just_audio: ^0.9.35
  audio_service: ^0.18.0
  just_audio_background: ^0.0.1-beta.17
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/